In [1]:
import numpy as np

## np.arange(), np.linspace(), np.logspace()

#### np.arange()

In [2]:
np.arange(0, 5, 1)

array([0, 1, 2, 3, 4])

In [3]:
np.arange(3, 15, 2)

array([ 3,  5,  7,  9, 11, 13])

In [4]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
list(range(2, 15, 4))

[2, 6, 10, 14]

In [9]:
np.arange(10, 1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

#### np.linspace()

In [12]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
np.linspace(0, 3, 10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

#### np.logspace()

In [14]:
np.logspace(0, 3, 10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

In [16]:
10 ** 0.3333

2.1542693374042363

#### linspace()とlogspace()で最後の要素を含みたくない場合はendpoint=Falseで未満の結果を出力可能

In [17]:
np.logspace(0, 3, 10, endpoint=False)

array([  1.        ,   1.99526231,   3.98107171,   7.94328235,
        15.84893192,  31.6227766 ,  63.09573445, 125.89254118,
       251.18864315, 501.18723363])

In [18]:
np.linspace(0, 3, 10, endpoint=False)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])