## ndarrayの演算

In [1]:
import numpy as np

In [3]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [4]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

#### 要素ごとの演算

#### listだとこのような演算ができないので注意

In [7]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [8]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

#### このように要素が一致しなくても自動で補ってくれる

#### Broadcastingという

In [9]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [10]:
ndarray + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])