## 数学で使う便利関数

In [1]:
import numpy as np

In [2]:
# 平方根 square root
np.sqrt([1, 2, 3, 4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [8]:
# log (logarithm)
x = np.linspace(1, 10, 10)
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [9]:
np.log2(x)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809])

In [18]:
# 指数関数 Exponential function
np.exp(1)

2.718281828459045

In [19]:
# 合計 (summation)
np.sum([1, 2, 3])

6

In [21]:
array = np.arange(1, 11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
np.sum(array)

55

In [26]:
ndarray = array.reshape(2, 5)
ndarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [25]:
np.sum(ndarray, axis=1)

array([15, 40])

In [27]:
# 絶対値 absolute value
#[-10, -9, -8]

array = np.arange(-10, 0)

In [28]:
np.abs(array)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])