## IndexingとSlicing

In [1]:
import numpy as np

## Indexing

In [2]:
ndarray = np.array([1, 2, 3, 4])

In [3]:
ndarray

array([1, 2, 3, 4])

In [5]:
ndarray[-1]

4

In [6]:
ndarray[0]

1

In [7]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])

In [8]:
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
ndarray[0, 1]

2

## slicing

In [11]:
ndarray = np.array([1, 2, 3, 4])
ndarray

array([1, 2, 3, 4])

In [12]:
ndarray[1:3]

array([2, 3])

#### 1以上3未満
#### ~ 以上 ~未満

In [13]:
ndarray[:3]

array([1, 2, 3])

In [14]:
ndarray[1:]

array([2, 3, 4])

In [15]:
ndarray[:-2]

array([1, 2])

In [16]:
ndarray[:]

array([1, 2, 3, 4])

In [17]:
ndarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [18]:
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
ndarray[:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
ndarray[:3, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [21]:
ndarray[:, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In [22]:
ndarray[:3][2:]

array([[ 9, 10, 11, 12]])