## NumPy Arrays (ndarray)

In [1]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [8]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [10]:
matrix[0]

array([1, 2, 3])

In [11]:
matrix[0][0]

1

In [12]:
type(matrix[0][0])

numpy.int64

In [13]:
type(1)

int

In [14]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### numpy.int64というデータタイプ(型)

#### numpy独自のデータタイプになっている

In [15]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=complex)

In [16]:
matrix

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

#### 要素のデータタイプを指定することも可能 

In [17]:
ndarray = np.array([1, 2, 3], dtype=np.uint8) # unsigned + - integer 8bit

#### uint8 はデータサイエンスでよく使う

#### dtype=np.uint8

#### unsigned, integer, 8bitのデータタイプ

#### unsignedは-+がないという意味

#### integerの8bitなので 2の8乗つまり　256 → 0~255までの値

#### 一般的には画像を扱うときに使う

In [18]:
ndarray

array([1, 2, 3], dtype=uint8)

In [19]:
ndarray = np.array([1, 2, 3], dtype=np.float32) 

In [21]:
ndarray

array([1., 2., 3.], dtype=float32)

#### 機械学習でデータを保存するときに使う

In [22]:
ndarray = np.array([1, 2, 3], dtype=np.float64) 

In [23]:
ndarray

array([1., 2., 3.])

#### 保存するときのデータ量が多いため実際のモデル学習に64bitで学習することが多い

In [25]:
ndarray.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

#### .astype()で元のndarrayのdtypeを変更