## NumPy Arrays (ndarray)

In [2]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [8]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [10]:
matrix[0]

array([1, 2, 3])

In [11]:
matrix[0][0]

1

In [12]:
type(matrix[0][0])

numpy.int64

In [13]:
type(1)

int

In [14]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### numpy.int64というデータタイプ(型)

#### numpy独自のデータタイプになっている

In [15]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=complex)

In [16]:
matrix

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

#### 要素のデータタイプを指定することも可能 

In [17]:
ndarray = np.array([1, 2, 3], dtype=np.uint8) # unsigned + - integer 8bit

#### uint8 はデータサイエンスでよく使う

#### dtype=np.uint8

#### unsigned, integer, 8bitのデータタイプ

#### unsignedは-+がないという意味

#### integerの8bitなので 2の8乗つまり　256 → 0~255までの値

#### 一般的には画像を扱うときに使う

In [18]:
ndarray

array([1, 2, 3], dtype=uint8)

In [19]:
ndarray = np.array([1, 2, 3], dtype=np.float32) 

In [21]:
ndarray

array([1., 2., 3.], dtype=float32)

#### 機械学習でデータを保存するときに使う

In [22]:
ndarray = np.array([1, 2, 3], dtype=np.float64) 

In [23]:
ndarray

array([1., 2., 3.])

#### 保存するときのデータ量が多いため実際のモデル学習に64bitで学習することが多い

In [25]:
ndarray.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

#### .astype()で元のndarrayのdtypeを変更

## np.save('path', array)とnp.load('path')

In [4]:
ndarray = np.random.randn(3, 4, 5)
ndarray.shape

(3, 4, 5)

In [6]:
np.save('sample_ndarray', ndarray)

In [9]:
loaded_ndarray = np.load('sample_ndarray.npy')
loaded_ndarray.shape

(3, 4, 5)

In [10]:
dictionary = {
    'id': 123456,
    'image': ndarray
}

In [11]:
dictionary

{'id': 123456,
 'image': array([[[-1.85869123,  1.20792693,  0.35415075, -0.1224539 ,
          -0.51483335],
         [-0.19818867, -1.29092425,  0.65145186,  0.13731711,
          -0.11077021],
         [-0.60308205, -0.38139361,  0.72501924,  0.79503581,
           0.31884103],
         [-0.17782918,  0.48434901,  1.5438977 , -1.27604427,
           0.6609939 ]],
 
        [[-0.31497495,  0.5856695 , -1.51268984, -0.83313901,
           0.32541835],
         [ 0.69305689,  0.49202025, -0.66913355, -0.07835382,
          -2.59589995],
         [-0.74686072,  1.05213627, -0.32338956,  0.06787359,
          -0.68858597],
         [ 0.71355676, -0.86741279, -0.31869782,  0.76019561,
          -0.39885469]],
 
        [[-0.80523241,  1.35513636,  0.01423522,  1.08327645,
          -0.30065564],
         [ 0.27032045,  0.29482027, -0.58879977, -0.48682014,
          -1.25991679],
         [-0.49005735,  1.61591409,  0.08583556, -2.08198802,
           0.73554327],
         [-1.86567119,  

In [12]:
np.save('sample_dict.npy', dictionary)

In [13]:
np.load('sample_dict.npy')

ValueError: Object arrays cannot be loaded when allow_pickle=False

In [14]:
np.load('sample_dict.npy', allow_pickle=True)

array({'id': 123456, 'image': array([[[-1.85869123,  1.20792693,  0.35415075, -0.1224539 ,
         -0.51483335],
        [-0.19818867, -1.29092425,  0.65145186,  0.13731711,
         -0.11077021],
        [-0.60308205, -0.38139361,  0.72501924,  0.79503581,
          0.31884103],
        [-0.17782918,  0.48434901,  1.5438977 , -1.27604427,
          0.6609939 ]],

       [[-0.31497495,  0.5856695 , -1.51268984, -0.83313901,
          0.32541835],
        [ 0.69305689,  0.49202025, -0.66913355, -0.07835382,
         -2.59589995],
        [-0.74686072,  1.05213627, -0.32338956,  0.06787359,
         -0.68858597],
        [ 0.71355676, -0.86741279, -0.31869782,  0.76019561,
         -0.39885469]],

       [[-0.80523241,  1.35513636,  0.01423522,  1.08327645,
         -0.30065564],
        [ 0.27032045,  0.29482027, -0.58879977, -0.48682014,
         -1.25991679],
        [-0.49005735,  1.61591409,  0.08583556, -2.08198802,
          0.73554327],
        [-1.86567119,  0.89282055, -0.0915

In [15]:
loaded_dict = np.load('sample_dict.npy', allow_pickle=True)

In [17]:
# loaded_dict

In [18]:
a = np.array({'a': 1})

In [19]:
a

array({'a': 1}, dtype=object)

In [20]:
a[()]

{'a': 1}

In [21]:
loaded_dict = np.load('sample_dict.npy', allow_pickle=True)[()]

In [22]:
type(loaded_dict)

dict

In [23]:
loaded_dict

{'id': 123456,
 'image': array([[[-1.85869123,  1.20792693,  0.35415075, -0.1224539 ,
          -0.51483335],
         [-0.19818867, -1.29092425,  0.65145186,  0.13731711,
          -0.11077021],
         [-0.60308205, -0.38139361,  0.72501924,  0.79503581,
           0.31884103],
         [-0.17782918,  0.48434901,  1.5438977 , -1.27604427,
           0.6609939 ]],
 
        [[-0.31497495,  0.5856695 , -1.51268984, -0.83313901,
           0.32541835],
         [ 0.69305689,  0.49202025, -0.66913355, -0.07835382,
          -2.59589995],
         [-0.74686072,  1.05213627, -0.32338956,  0.06787359,
          -0.68858597],
         [ 0.71355676, -0.86741279, -0.31869782,  0.76019561,
          -0.39885469]],
 
        [[-0.80523241,  1.35513636,  0.01423522,  1.08327645,
          -0.30065564],
         [ 0.27032045,  0.29482027, -0.58879977, -0.48682014,
          -1.25991679],
         [-0.49005735,  1.61591409,  0.08583556, -2.08198802,
           0.73554327],
         [-1.86567119,  