## その他の便利関数

In [1]:
import numpy as np

#### np.clip()

In [2]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.clip(array, 3, 7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

In [5]:
1e-4

0.0001

## numpy array の condition

In [7]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### np.where

In [8]:
np.where(array > 3, 1, 0)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [15]:
result, = np.where(array > 3)

In [16]:
result

array([4, 5, 6, 7, 8, 9])

In [13]:
# filter
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [14]:
array[array > 3]

array([4, 5, 6, 7, 8, 9])

In [18]:
ndarray = array.reshape(2, 5)
ndarray[ndarray>3]

array([4, 5, 6, 7, 8, 9])

In [22]:
ndarray > 3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [23]:
# 全てTrue?
(ndarray > 3).all()

False

In [25]:
# 1つでもTrue?
(ndarray > 3).any()

True

In [26]:
(ndarray > 3).all(axis=1)

array([False,  True])

#### np.unique()

In [28]:
array = np.array([1, 1, 2, 3, 4, 2, 3, 4, 5])
array

array([1, 1, 2, 3, 4, 2, 3, 4, 5])

In [29]:
np.unique(array)

array([1, 2, 3, 4, 5])

In [30]:
np.unique(array, return_counts=True)

(array([1, 2, 3, 4, 5]), array([2, 2, 2, 2, 1]))

#### np.bincount()

In [31]:
np.bincount(array)

array([0, 2, 2, 2, 2, 1])