## その他の便利関数

In [1]:
import numpy as np

#### np.clip()

In [2]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.clip(array, 3, 7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

In [5]:
1e-4

0.0001

## numpy array の condition

In [7]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### np.where

In [8]:
np.where(array > 3, 1, 0)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [15]:
result, = np.where(array > 3)

In [16]:
result

array([4, 5, 6, 7, 8, 9])

In [13]:
# filter
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [14]:
array[array > 3]

array([4, 5, 6, 7, 8, 9])

In [18]:
ndarray = array.reshape(2, 5)
ndarray[ndarray>3]

array([4, 5, 6, 7, 8, 9])

In [22]:
ndarray > 3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [23]:
# 全てTrue?
(ndarray > 3).all()

False

In [25]:
# 1つでもTrue?
(ndarray > 3).any()

True

In [26]:
(ndarray > 3).all(axis=1)

array([False,  True])

#### np.unique()

In [28]:
array = np.array([1, 1, 2, 3, 4, 2, 3, 4, 5])
array

array([1, 1, 2, 3, 4, 2, 3, 4, 5])

In [29]:
np.unique(array)

array([1, 2, 3, 4, 5])

In [30]:
np.unique(array, return_counts=True)

(array([1, 2, 3, 4, 5]), array([2, 2, 2, 2, 1]))

#### np.bincount()

In [31]:
np.bincount(array)

array([0, 2, 2, 2, 2, 1])

## np.concatenate()とstack()

In [33]:
ndarray_even = np.arange(0, 18, 2).reshape(3, 3)
ndarray_even

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [44]:
ndarray_odd = np.arange(1, 19, 2).reshape(3, 3)
ndarray_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [45]:
np.concatenate([ndarray_even, ndarray_odd])

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [46]:
np.concatenate([ndarray_even, ndarray_odd], axis=1)

array([[ 0,  2,  4,  1,  3,  5],
       [ 6,  8, 10,  7,  9, 11],
       [12, 14, 16, 13, 15, 17]])

In [47]:
np.stack([ndarray_even, ndarray_odd])

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]])

In [48]:
_

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]])

In [49]:
stacked_array = _

In [50]:
stacked_array

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]])

In [51]:
stacked_array.shape

(2, 3, 3)

In [52]:
np.stack([ndarray_even, ndarray_odd], axis=-1)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

## np.transpose .T

In [57]:
ndarray = np.random.randn(3, 4)
ndarray

array([[-1.00736532,  0.19707413,  0.82444086, -0.68167239],
       [ 1.05032079, -1.07383417, -0.98550569, -0.07445885],
       [ 0.44112511,  1.13119125, -1.71781262, -1.80649638]])

In [58]:
ndarray.shape

(3, 4)

In [59]:
np.transpose(ndarray)

array([[-1.00736532,  1.05032079,  0.44112511],
       [ 0.19707413, -1.07383417,  1.13119125],
       [ 0.82444086, -0.98550569, -1.71781262],
       [-0.68167239, -0.07445885, -1.80649638]])

In [60]:
transpose_ndarray = _

In [61]:
transpose_ndarray.shape

(4, 3)

In [62]:
ndarray.T

array([[-1.00736532,  1.05032079,  0.44112511],
       [ 0.19707413, -1.07383417,  1.13119125],
       [ 0.82444086, -0.98550569, -1.71781262],
       [-0.68167239, -0.07445885, -1.80649638]])

In [63]:
ndarray = np.random.randn(3, 4, 5)

In [64]:
ndarray.T.shape

(5, 4, 3)