## np.randomを使って乱数生成

In [1]:
import numpy as np

### np.random.rand()

In [7]:
## 擬似乱数 pseudo random
np.random.rand(3, 4)

array([[0.17554546, 0.39143012, 0.52574702, 0.15033728],
       [0.27259531, 0.96332419, 0.70503985, 0.10866569],
       [0.07677691, 0.73690336, 0.16649326, 0.70730071]])

### np.random.seed

In [10]:
np.random.seed(1)
np.random.rand()

0.417022004702574

#### データサイエンスでは再現させることができるように乱数生成にはなるべくseedを使う

In [11]:
np.random.rand()

0.7203244934421581

#### jupyterlabでは２回目のnp.random.rand()をするとランダムに乱数を生成するので注意

## 正規分布
## np.random.randn()

#### 平均が0 分散が1の時 「標準正規分布」　という

In [18]:
np.random.randn()

0.31903909605709857

#### np.random.randn()
#### 標準正規分布(平均0, 分散1)からランダムの値が返される

In [19]:
np.random.randn(10, 10)

array([[-0.24937038,  1.46210794, -2.06014071, -0.3224172 , -0.38405435,
         1.13376944, -1.09989127, -0.17242821, -0.87785842,  0.04221375],
       [ 0.58281521, -1.10061918,  1.14472371,  0.90159072,  0.50249434,
         0.90085595, -0.68372786, -0.12289023, -0.93576943, -0.26788808],
       [ 0.53035547, -0.69166075, -0.39675353, -0.6871727 , -0.84520564,
        -0.67124613, -0.0126646 , -1.11731035,  0.2344157 ,  1.65980218],
       [ 0.74204416, -0.19183555, -0.88762896, -0.74715829,  1.6924546 ,
         0.05080775, -0.63699565,  0.19091548,  2.10025514,  0.12015895],
       [ 0.61720311,  0.30017032, -0.35224985, -1.1425182 , -0.34934272,
        -0.20889423,  0.58662319,  0.83898341,  0.93110208,  0.28558733],
       [ 0.88514116, -0.75439794,  1.25286816,  0.51292982, -0.29809284,
         0.48851815, -0.07557171,  1.13162939,  1.51981682,  2.18557541],
       [-1.39649634, -1.44411381, -0.50446586,  0.16003707,  0.87616892,
         0.31563495, -2.02220122, -0.30620401

## np.random.normal()

In [20]:
np.random.normal(10, 1)

10.032614546693358

## np.random.randint()

In [24]:
np.random.randint(10, 100, (2, 3))

array([[93, 48, 57],
       [15, 89, 73]])

In [34]:
np.random.randint(10)

4

## np.random.choice()

In [35]:
a = [1, 2, 3]
np.random.choice(a)

3

In [38]:
index_pool = np.arange(0, 10, 2)
index_pool

array([0, 2, 4, 6, 8])

In [43]:
np.random.choice(index_pool)

8