## Shape

In [1]:
import numpy as np

In [4]:
ndarray = np.array([[1,2], [3, 4], [5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
ndarray.shape

(3, 2)

In [6]:
ndarray.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
ndarray.reshape(1, 3)

ValueError: cannot reshape array of size 6 into shape (1,3)

In [8]:
ndarray1 = np.array([1, 2, 3])
ndarray2 = np.array([[1, 2, 3]])

In [13]:
array1

array([1, 2])

In [9]:
print(ndarray1.shape)

(3,)


In [12]:
ndarray2

array([[1, 2, 3]])

In [10]:
print(ndarray2.shape)

(1, 3)


#### 次元を増やす関数
#### np.expand_dims(ndarray, axis)
#### ndarrayの次元を増やす

In [14]:
np.expand_dims(ndarray1, axis=0)

array([[1, 2, 3]])

In [15]:
np.expand_dims(ndarray1, axis=1)

array([[1],
       [2],
       [3]])

In [16]:
expand_ndarray = np.expand_dims(ndarray1, axis=1)

In [17]:
expand_ndarray.shape

(3, 1)

#### 次元を減らす
#### np.squeeze(ndarray)
#### squeeze→絞る(減らす)

In [18]:
np.squeeze(expand_ndarray)

array([1, 2, 3])

In [19]:
expand_ndarray

array([[1],
       [2],
       [3]])

#### ndarrayを１次元にする
#### .flatten()

In [21]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ndarray.shape

(3, 3)

In [22]:
ndarray.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])