## 統計量を求める

In [1]:
import numpy as np

In [2]:
std_norm = np.random.randn(5, 5)
std_norm

array([[ 1.56662941,  0.05507619,  1.35697191,  0.18635903,  2.06180451],
       [-0.16502859,  0.20061908, -0.7789759 ,  1.29841482, -0.20727353],
       [-0.50124824, -1.99441175, -0.17178848, -0.41228614,  0.33987809],
       [ 1.87937471,  0.54483384, -0.00414291, -1.26655719, -1.17740552],
       [-0.36110154,  1.47147818, -0.14550529, -2.097606  , -0.3574902 ]])

In [3]:
# 最大量
std_norm.max()

2.061804513368536

In [4]:
np.max(std_norm)

2.061804513368536

In [5]:
# 最小値
std_norm.min()

-2.0976059991520866

In [6]:
# 最大値のindexを取得
std_norm.argmax()

4

In [7]:
std_norm.flatten()[4]

2.061804513368536

In [8]:
# 最小値のindexを取得
std_norm.argmin()

23

In [9]:
std_norm.flatten()[23]

-2.0976059991520866

In [10]:
# 平均を取得
std_norm.mean()

0.05282473986926093

In [12]:
# 中央値を取得 （注意）
np.median(std_norm)

-0.145505285476558

#### 中央値は平均値をより求める時間がかかる
#### 中央値は並び替える必要があるためデータが多くなれななるほど時間がかかる
#### はずれ値には強い

In [16]:
# 中央値 vs 平均値
import time
a = np.random.randn(1000, 1000)
before = time.time()
np.median(a)
after_median = time.time()
np.mean(a)
after_mean = time.time()
print('median took {} sec'.format(after_median - before))
print('mean took {} sec'.format(after_mean - after_median))

median took 0.02637791633605957 sec
mean took 0.0016334056854248047 sec


In [17]:
# 標準偏差の取得
np.std(std_norm)

1.079365205521851

In [21]:
# 列ごと
std_norm.max(axis=0)

array([1.87937471, 1.47147818, 1.35697191, 1.29841482, 2.06180451])

In [22]:
# 行ごと
std_norm.max(axis=1)

array([2.06180451, 1.29841482, 0.33987809, 1.87937471, 1.47147818])

#### axisを使うことで列、行ごとで最大の統計量を求めることができる