In [1]:
import numpy as np

## .zeros()
#### 要素が全て0のndarray
#### np.zeros(shape)

In [3]:
shape = (3, 4)
np.zeros(shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.zeros(3)

array([0., 0., 0.])

## .ones()
#### 要素が全て1のndarray
#### np.ones()

In [5]:
shape = (5, 4)
np.ones(shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.ones(3)

array([1., 1., 1.])

In [8]:
np.ones((5, 4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

## .eye()
#### 対角要素が全て1のndarray
#### np.eye()

In [9]:
# I (identify matrix)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])